version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password@123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  drones_api:
    image: dronesapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DbServer : "db"
      DbPort: "1433"
      DbUser: "SA"
      Password: "Password@123"
      Database: "DronesDb"
    ports:
      - "8090:80"
    depends_on:
      - db