// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using drones_api.Data;

namespace drones_api.Migrations
{
    [DbContext(typeof(DronesApiContext))]
    [Migration("20211124001747_ModelLengthAdjustMent")]
    partial class ModelLengthAdjustMent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("drones_api.Models.DroneModel", b =>
                {
                    b.Property<Guid>("DroneModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(90)")
                        .HasMaxLength(90);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DroneModelId");

                    b.HasIndex("ModelName")
                        .IsUnique();

                    b.ToTable("DroneModels");

                    b.HasData(
                        new
                        {
                            DroneModelId = new Guid("9126a1f5-3d39-41bf-bed0-4fb6c4a36111"),
                            CreatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 791, DateTimeKind.Local).AddTicks(4732),
                            ModelName = "Lightweight",
                            UpdatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 792, DateTimeKind.Local).AddTicks(9330)
                        },
                        new
                        {
                            DroneModelId = new Guid("65a9dcb1-f0a6-4550-8d15-8834a20abb09"),
                            CreatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 793, DateTimeKind.Local).AddTicks(791),
                            ModelName = "MiddleWeight",
                            UpdatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 793, DateTimeKind.Local).AddTicks(824)
                        },
                        new
                        {
                            DroneModelId = new Guid("88fe4536-3048-4af6-bbfd-2fd78b944db7"),
                            CreatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 793, DateTimeKind.Local).AddTicks(853),
                            ModelName = "Cruiserweight",
                            UpdatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 793, DateTimeKind.Local).AddTicks(855)
                        },
                        new
                        {
                            DroneModelId = new Guid("12d55a62-b6f4-4cff-824c-c556154cefed"),
                            CreatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 793, DateTimeKind.Local).AddTicks(864),
                            ModelName = "Heavyweight",
                            UpdatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 793, DateTimeKind.Local).AddTicks(866)
                        });
                });

            modelBuilder.Entity("drones_api.Models.DroneState", b =>
                {
                    b.Property<Guid>("DroneStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DroneStateId");

                    b.ToTable("DroneStates");

                    b.HasData(
                        new
                        {
                            DroneStateId = new Guid("ad81e5c9-0e01-4e4f-bb70-63accc2e23cb"),
                            CreatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 796, DateTimeKind.Local).AddTicks(3275),
                            StateTitle = "IDLE",
                            UpdatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 796, DateTimeKind.Local).AddTicks(4220)
                        },
                        new
                        {
                            DroneStateId = new Guid("d94c7160-1dd0-4dfe-b4e3-384158b4c2e6"),
                            CreatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 796, DateTimeKind.Local).AddTicks(5039),
                            StateTitle = "LOADING",
                            UpdatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 796, DateTimeKind.Local).AddTicks(5073)
                        },
                        new
                        {
                            DroneStateId = new Guid("bccb4855-9c1d-4b17-98f0-9f6698a40641"),
                            CreatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 796, DateTimeKind.Local).AddTicks(5098),
                            StateTitle = "LOADED",
                            UpdatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 796, DateTimeKind.Local).AddTicks(5100)
                        },
                        new
                        {
                            DroneStateId = new Guid("952119b5-d401-4e76-ac7a-d77573aa4618"),
                            CreatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 796, DateTimeKind.Local).AddTicks(5104),
                            StateTitle = "DELIVERING",
                            UpdatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 796, DateTimeKind.Local).AddTicks(5106)
                        },
                        new
                        {
                            DroneStateId = new Guid("bee56edf-5ef5-4ece-892e-c679dfebcbb7"),
                            CreatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 796, DateTimeKind.Local).AddTicks(5109),
                            StateTitle = "DELIVERED",
                            UpdatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 796, DateTimeKind.Local).AddTicks(5111)
                        },
                        new
                        {
                            DroneStateId = new Guid("60936034-248e-43a5-ab5b-0ea3f8b0ca6c"),
                            CreatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 796, DateTimeKind.Local).AddTicks(5114),
                            StateTitle = "RETURNING",
                            UpdatedAt = new DateTime(2021, 11, 24, 1, 17, 46, 796, DateTimeKind.Local).AddTicks(5116)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
