// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using drones_api.Data;

namespace drones_api.Migrations
{
    [DbContext(typeof(DronesApiContext))]
    [Migration("20211124093030_DroneMigration")]
    partial class DroneMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("drones_api.Models.Drone", b =>
                {
                    b.Property<Guid>("DroneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BatterCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WeightLimit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DroneId");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.ToTable("Drones");
                });

            modelBuilder.Entity("drones_api.Models.DroneModel", b =>
                {
                    b.Property<Guid>("DroneModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(90)")
                        .HasMaxLength(90);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DroneModelId");

                    b.HasIndex("ModelName")
                        .IsUnique();

                    b.ToTable("DroneModels");

                    b.HasData(
                        new
                        {
                            DroneModelId = new Guid("8af14faf-d8d9-4ab6-9281-dacb4ae340ef"),
                            CreatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 73, DateTimeKind.Local).AddTicks(2259),
                            ModelName = "Lightweight",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 73, DateTimeKind.Local).AddTicks(9610)
                        },
                        new
                        {
                            DroneModelId = new Guid("91d7c4cd-1b96-4546-abcf-b8e086b26995"),
                            CreatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 74, DateTimeKind.Local).AddTicks(109),
                            ModelName = "MiddleWeight",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 74, DateTimeKind.Local).AddTicks(119)
                        },
                        new
                        {
                            DroneModelId = new Guid("8f4f64b0-b0e8-4e96-a555-7eac8ba66505"),
                            CreatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 74, DateTimeKind.Local).AddTicks(127),
                            ModelName = "Cruiserweight",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 74, DateTimeKind.Local).AddTicks(128)
                        },
                        new
                        {
                            DroneModelId = new Guid("1daa4db5-0ce9-4cb3-9388-fd4317cb3904"),
                            CreatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 74, DateTimeKind.Local).AddTicks(130),
                            ModelName = "Heavyweight",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 74, DateTimeKind.Local).AddTicks(131)
                        });
                });

            modelBuilder.Entity("drones_api.Models.DroneState", b =>
                {
                    b.Property<Guid>("DroneStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DroneStateId");

                    b.HasIndex("StateTitle")
                        .IsUnique();

                    b.ToTable("DroneStates");

                    b.HasData(
                        new
                        {
                            DroneStateId = new Guid("b5b6a5cd-ebc0-434d-a1a6-38556840948f"),
                            CreatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 75, DateTimeKind.Local).AddTicks(3901),
                            StateTitle = "IDLE",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 75, DateTimeKind.Local).AddTicks(4376)
                        },
                        new
                        {
                            DroneStateId = new Guid("a9715d4a-6ebd-450b-b55b-751a9faadd00"),
                            CreatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 75, DateTimeKind.Local).AddTicks(4727),
                            StateTitle = "LOADING",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 75, DateTimeKind.Local).AddTicks(4742)
                        },
                        new
                        {
                            DroneStateId = new Guid("cc19ad1e-7fd1-4094-9bef-ee9d7d5d7360"),
                            CreatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 75, DateTimeKind.Local).AddTicks(4753),
                            StateTitle = "LOADED",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 75, DateTimeKind.Local).AddTicks(4754)
                        },
                        new
                        {
                            DroneStateId = new Guid("2035fb8d-f31c-4225-be3a-b250fb704fb9"),
                            CreatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 75, DateTimeKind.Local).AddTicks(4756),
                            StateTitle = "DELIVERING",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 75, DateTimeKind.Local).AddTicks(4757)
                        },
                        new
                        {
                            DroneStateId = new Guid("0c00ee4e-b6f7-4fe7-94ed-ed5abd2a73d3"),
                            CreatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 75, DateTimeKind.Local).AddTicks(4758),
                            StateTitle = "DELIVERED",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 75, DateTimeKind.Local).AddTicks(4759)
                        },
                        new
                        {
                            DroneStateId = new Guid("a9588e8b-486f-45f1-bb83-d02bee9a2d3b"),
                            CreatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 75, DateTimeKind.Local).AddTicks(4761),
                            StateTitle = "RETURNING",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 10, 30, 30, 75, DateTimeKind.Local).AddTicks(4762)
                        });
                });

            modelBuilder.Entity("drones_api.Models.Medication", b =>
                {
                    b.Property<Guid>("MedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MedicationId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Medication");
                });
#pragma warning restore 612, 618
        }
    }
}
