// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using drones_api.Data;

namespace drones_api.Migrations
{
    [DbContext(typeof(DronesApiContext))]
    [Migration("20211124012422_DroneModelStatus")]
    partial class DroneModelStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("drones_api.Models.DroneModel", b =>
                {
                    b.Property<Guid>("DroneModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(90)")
                        .HasMaxLength(90);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DroneModelId");

                    b.HasIndex("ModelName")
                        .IsUnique();

                    b.ToTable("DroneModels");

                    b.HasData(
                        new
                        {
                            DroneModelId = new Guid("853fc8f5-804f-47ad-a0eb-e7769d5874e5"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 841, DateTimeKind.Local).AddTicks(7967),
                            ModelName = "Lightweight",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 842, DateTimeKind.Local).AddTicks(5390)
                        },
                        new
                        {
                            DroneModelId = new Guid("6e1dda1d-ec99-4253-9ddc-79cd8a4505b4"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 842, DateTimeKind.Local).AddTicks(5911),
                            ModelName = "MiddleWeight",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 842, DateTimeKind.Local).AddTicks(5922)
                        },
                        new
                        {
                            DroneModelId = new Guid("54c23318-e002-4f14-b978-766d215968e9"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 842, DateTimeKind.Local).AddTicks(5929),
                            ModelName = "Cruiserweight",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 842, DateTimeKind.Local).AddTicks(5930)
                        },
                        new
                        {
                            DroneModelId = new Guid("c39227a1-4151-49ca-ad64-e26470b63ced"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 842, DateTimeKind.Local).AddTicks(5932),
                            ModelName = "Heavyweight",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 842, DateTimeKind.Local).AddTicks(5933)
                        });
                });

            modelBuilder.Entity("drones_api.Models.DroneState", b =>
                {
                    b.Property<Guid>("DroneStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DroneStateId");

                    b.ToTable("DroneStates");

                    b.HasData(
                        new
                        {
                            DroneStateId = new Guid("0d98f1ad-d5be-494a-99f0-f9122a5b1b52"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 844, DateTimeKind.Local).AddTicks(341),
                            StateTitle = "IDLE",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 844, DateTimeKind.Local).AddTicks(684)
                        },
                        new
                        {
                            DroneStateId = new Guid("f627e554-5135-4195-883d-5793a6aa08ad"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 844, DateTimeKind.Local).AddTicks(1027),
                            StateTitle = "LOADING",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 844, DateTimeKind.Local).AddTicks(1045)
                        },
                        new
                        {
                            DroneStateId = new Guid("be9328f8-9164-498e-bd00-8641bd9f4010"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 844, DateTimeKind.Local).AddTicks(1053),
                            StateTitle = "LOADED",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 844, DateTimeKind.Local).AddTicks(1054)
                        },
                        new
                        {
                            DroneStateId = new Guid("d5c7e97e-23e7-4dbb-82fd-3168b9bee5ea"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 844, DateTimeKind.Local).AddTicks(1056),
                            StateTitle = "DELIVERING",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 844, DateTimeKind.Local).AddTicks(1057)
                        },
                        new
                        {
                            DroneStateId = new Guid("7e07094c-8b12-44f4-bdb7-8b75a3d83c96"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 844, DateTimeKind.Local).AddTicks(1066),
                            StateTitle = "DELIVERED",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 844, DateTimeKind.Local).AddTicks(1067)
                        },
                        new
                        {
                            DroneStateId = new Guid("282c8168-3068-42a5-8b64-cd8eff569d37"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 844, DateTimeKind.Local).AddTicks(1069),
                            StateTitle = "RETURNING",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 24, 21, 844, DateTimeKind.Local).AddTicks(1070)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
