// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using drones_api.Data;

namespace drones_api.Migrations
{
    [DbContext(typeof(DronesApiContext))]
    [Migration("20211124015755_DroneStateStatus")]
    partial class DroneStateStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("drones_api.Models.DroneModel", b =>
                {
                    b.Property<Guid>("DroneModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(90)")
                        .HasMaxLength(90);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DroneModelId");

                    b.HasIndex("ModelName")
                        .IsUnique();

                    b.ToTable("DroneModels");

                    b.HasData(
                        new
                        {
                            DroneModelId = new Guid("9d615c07-8d8f-4701-a1a4-57876cd5ebe7"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 726, DateTimeKind.Local).AddTicks(9425),
                            ModelName = "Lightweight",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 727, DateTimeKind.Local).AddTicks(6726)
                        },
                        new
                        {
                            DroneModelId = new Guid("8ae918f2-8c70-440e-a1fd-f235c0ffedf7"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 727, DateTimeKind.Local).AddTicks(7247),
                            ModelName = "MiddleWeight",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 727, DateTimeKind.Local).AddTicks(7259)
                        },
                        new
                        {
                            DroneModelId = new Guid("65e92421-95f6-491a-a725-df8add6a089b"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 727, DateTimeKind.Local).AddTicks(7272),
                            ModelName = "Cruiserweight",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 727, DateTimeKind.Local).AddTicks(7272)
                        },
                        new
                        {
                            DroneModelId = new Guid("51a94f4c-745c-4bf4-bcc7-1a90ac06545b"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 727, DateTimeKind.Local).AddTicks(7274),
                            ModelName = "Heavyweight",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 727, DateTimeKind.Local).AddTicks(7275)
                        });
                });

            modelBuilder.Entity("drones_api.Models.DroneState", b =>
                {
                    b.Property<Guid>("DroneStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DroneStateId");

                    b.ToTable("DroneStates");

                    b.HasData(
                        new
                        {
                            DroneStateId = new Guid("63b7ba4b-3cfa-4df2-83cb-877db0824aca"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 729, DateTimeKind.Local).AddTicks(1964),
                            StateTitle = "IDLE",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 729, DateTimeKind.Local).AddTicks(2267)
                        },
                        new
                        {
                            DroneStateId = new Guid("0ff1e5af-c797-4fd6-9bc9-df279ad144f4"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 729, DateTimeKind.Local).AddTicks(2590),
                            StateTitle = "LOADING",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 729, DateTimeKind.Local).AddTicks(2607)
                        },
                        new
                        {
                            DroneStateId = new Guid("ffe405c8-4237-4789-8c38-1e3dd894cc9d"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 729, DateTimeKind.Local).AddTicks(2617),
                            StateTitle = "LOADED",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 729, DateTimeKind.Local).AddTicks(2618)
                        },
                        new
                        {
                            DroneStateId = new Guid("5dc064cc-1349-446d-95f7-6e9b116cd14c"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 729, DateTimeKind.Local).AddTicks(2620),
                            StateTitle = "DELIVERING",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 729, DateTimeKind.Local).AddTicks(2621)
                        },
                        new
                        {
                            DroneStateId = new Guid("6c7d7f60-3f2f-4ad6-9a3d-c41c34b82e9e"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 729, DateTimeKind.Local).AddTicks(2633),
                            StateTitle = "DELIVERED",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 729, DateTimeKind.Local).AddTicks(2634)
                        },
                        new
                        {
                            DroneStateId = new Guid("7d37b2e2-18db-4c09-96ed-3aebc1a44371"),
                            CreatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 729, DateTimeKind.Local).AddTicks(2636),
                            StateTitle = "RETURNING",
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 11, 24, 2, 57, 54, 729, DateTimeKind.Local).AddTicks(2637)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
