// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using drones_api.Data;

namespace drones_api.Migrations
{
    [DbContext(typeof(DronesApiContext))]
    partial class DronesApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("drones_api.Models.DroneModel", b =>
                {
                    b.Property<Guid>("DroneModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DroneModelId");

                    b.ToTable("DroneModels");

                    b.HasData(
                        new
                        {
                            DroneModelId = new Guid("1f918515-5c2f-4517-9299-4583849cfc05"),
                            CreatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 547, DateTimeKind.Local).AddTicks(7041),
                            ModelName = "Lightweight",
                            UpdatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 548, DateTimeKind.Local).AddTicks(6682)
                        },
                        new
                        {
                            DroneModelId = new Guid("35352b29-8623-49b2-b9aa-3781bbd7b1ea"),
                            CreatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 548, DateTimeKind.Local).AddTicks(7385),
                            ModelName = "MiddleWeight",
                            UpdatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 548, DateTimeKind.Local).AddTicks(7399)
                        },
                        new
                        {
                            DroneModelId = new Guid("71f3b997-1321-4baa-8c35-a1194f022916"),
                            CreatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 548, DateTimeKind.Local).AddTicks(7409),
                            ModelName = "Cruiserweight",
                            UpdatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 548, DateTimeKind.Local).AddTicks(7410)
                        },
                        new
                        {
                            DroneModelId = new Guid("01147346-ba7f-4031-810b-8bf83c870193"),
                            CreatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 548, DateTimeKind.Local).AddTicks(7413),
                            ModelName = "Heavyweight",
                            UpdatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 548, DateTimeKind.Local).AddTicks(7414)
                        });
                });

            modelBuilder.Entity("drones_api.Models.DroneState", b =>
                {
                    b.Property<Guid>("DroneStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DroneStateId");

                    b.ToTable("DroneStates");

                    b.HasData(
                        new
                        {
                            DroneStateId = new Guid("9cdf1ad6-5546-4a72-abad-f4edc8f5ba46"),
                            CreatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 550, DateTimeKind.Local).AddTicks(5981),
                            StateTitle = "IDLE",
                            UpdatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 550, DateTimeKind.Local).AddTicks(6361)
                        },
                        new
                        {
                            DroneStateId = new Guid("3e4cfe25-0ef5-4b97-8fb8-f520bf0201c7"),
                            CreatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 550, DateTimeKind.Local).AddTicks(6788),
                            StateTitle = "LOADING",
                            UpdatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 550, DateTimeKind.Local).AddTicks(6810)
                        },
                        new
                        {
                            DroneStateId = new Guid("3fb1c619-463b-49f5-8264-5174bfc07dbc"),
                            CreatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 550, DateTimeKind.Local).AddTicks(6823),
                            StateTitle = "LOADED",
                            UpdatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 550, DateTimeKind.Local).AddTicks(6824)
                        },
                        new
                        {
                            DroneStateId = new Guid("f83ff7d2-049f-4983-b774-da97b2de3bc8"),
                            CreatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 550, DateTimeKind.Local).AddTicks(6826),
                            StateTitle = "DELIVERING",
                            UpdatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 550, DateTimeKind.Local).AddTicks(6828)
                        },
                        new
                        {
                            DroneStateId = new Guid("33058348-c7bc-40df-8f09-63b2c79f4635"),
                            CreatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 550, DateTimeKind.Local).AddTicks(6844),
                            StateTitle = "DELIVERED",
                            UpdatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 550, DateTimeKind.Local).AddTicks(6845)
                        },
                        new
                        {
                            DroneStateId = new Guid("e2e5f920-c053-4a03-bb1f-97d108ea3897"),
                            CreatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 550, DateTimeKind.Local).AddTicks(6848),
                            StateTitle = "RETURNING",
                            UpdatedAt = new DateTime(2021, 11, 22, 0, 14, 45, 550, DateTimeKind.Local).AddTicks(6850)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
